/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codedok.java8.tutorial;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
