# Logging
logging:
  file: app.log

# web server config
server:
  port: 8181
  servlet:
    context-path: /web
    
# spring config    
spring:
  profiles:
    active:
    - prod
  # Spring Security default user name and password 
  security:
    user:
      name: admin
      password: 123456!
      roles:
      - ACTUATOR_ADMIN
# INFO ENDPOINT CONFIGURATION
info: 
  app: 
    name: n @project.name@
    description: d @project.description@
    version: v @project.version@
    encoding: e @project.build.sourceEncoding@
    java: 
      version: v @java.version@
      
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  # 访问地址：http://localhost:8090/actuator/health
  server:
    port: 8090
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
    shutdown: 
      enabled: true
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'